### PR TITLE
Created en_GB.lang

### PR DESCRIPTION
**Pull request by Chocohead**
Not massively different from the en_US version, but that's expected.

### CODE REVIEW

**Comment by binnie567** [comment]
I'm intrigued what the changes were, considering I tend to use UK spellings anyway

**Comment by TimoMeijer** [comment]
I diffed one file, and to me it seems to mostly fix spelling errors, not add alternatives. It seems like these changes could better be merged with the en_US translation file.
https://www.diffchecker.com/rmt008b6

**Comment by Chocohead** [comment]
I expected the en_US to change again to change away from things like colour, the spelling corrections just happened along the way. There are still things like gray -> grey ;)

**Comment by binnie567** [comment]
Good point, I may just start making the en_GB versions the one I edit and add new localisations to, considering that that is the spelling style I (evidently sometimes miss) use

**Pull request merged**
